---
title: "Séance de travaux dirigés 4"
output: html_document
---

** **

#### [Questions de cours](http://francoio.github.io/html/CM4.html) 

* Rappeler la définition de la [loi de Poisson](https://fr.wikipedia.org/wiki/Loi_de_Poisson) de paramètre $\lambda >0$.

* Rappeler l'espérance de la loi de Poisson.

* Rappeler le théorème de transfert pour une loi discrète. 

* Rappeler la formule de conditionnement pour une loi discrète. 

** **




#### Exercice 1

Au [football](https://fr.wikipedia.org/wiki/Lois_du_jeu), on peut normalement marquer des buts de la tête ou du pied. On suppose que le nombre de buts marqués lors d'une partie est un nombre aléatoire $K$ tiré suivant la loi de Poisson de paramètre $\lambda >0$.

La probabilité pour qu'un but soit marqué de la tête est $p$, $0 < p < 1$, et on suppose que les buts sont marqués indépendamment les uns des autres. 

##### Question 1

* Sachant que $K = k$ buts ont été marqués lors d'une partie, montrer que la probabilité conditionnelle  pour que $L = \ell$ buts soient marqués de la tête est 
$$
{\rm P} (L = \ell ~|~ K = k ) = \frac{k!}{\ell! (k - \ell)!} p^\ell (1 - p)^{k - \ell} , \quad \ell = 0, \dots, k
$$

##### Question 2

* En déduire la probabilité que l'on observe $L = \ell$ buts marqués de la tête lors d'une partie.

* Calculer l'espérance de la variable aléatoire $L$.

##### Question 3

En fait, le modèle est imparfait et il existe une probabilité $\epsilon>0$ pour qu'un but soit [marqué de la main](https://es.wikipedia.org/wiki/La_mano_de_Dios). 

* Quelle est la probabilité d'observer au moins un but marqué de la main lors d'une partie ? 


** **

#### Exercice 2

Un rat se trouve dans un labyrinthe face à deux portes. Il choisit la première de ces deux portes avec probabilité 1/3 et la deuxième porte avec probabilité 2/3. Quand il choisit la première porte, il revient à son point de départ en une minute. Quand il choisit la deuxième porte, il effectue un trajet d’une minute jusqu’à un point intermédiaire, puis il rebrousse chemin avec la probabilité 1/2 (le retour lui prend alors une minute) ou il sort du labyrinthe en une minute avec la probabilité 1/2. Tous les choix du rat se font indépendamment les uns des autres.

Soit $T$ le temps passé par le rat dans le labyrinthe. On cherche à déterminer l'espérance de $T$, puis la loi de $T$. 

** **

##### Question 1 

Soit $N$ le numéro de la porte choisie au départ du rat. 

* Etablir une relation simple reliant E$[T|N=1]$ et E$[T]$.

* Etablir une relation similaire reliant E$[T|N=1]$ et E$[T]$.

* Appliquer la formule de conditionnement et en déduire la valeur de E$[T]$.

** ** 

##### Question 2

On note $d, i$ et $s$ les points de départ, intermédiaire et de sortie du rat, et on note $X_n$ la suite aléatoire des points visités par le rat. 

* Trouver la relation entre la loi de $T$ et les probabilités conditionnelles $p_{ds}^n =$ P$(X_n = s|X_0=d)$.

* Montrer par récurrence, que l'on a, la relation suivante

$$
p_{ds}^{n+1}  = \frac13 ( p_{ds}^{n} + p_{ds}^{n-1} + 1).
$$

* Résoudre cette équation et en déduire la loi de $T$. Retrouver l'espérance de $T$ par le calcul direct. 


** ** 







Soien 
