---
title: "Test 0 -- TD-1"
output: html_document
---

** **

Le formulaire de réponse [Formulaire-Test-0-Prénom-Nom.Rmd](https://github.com/francoio/francoio.github.io) à compléter et à déposer dans TEIDE.

** **

#### Problème 1 

Eva et Raph jouent aux dés (supposés équilibrés). Eva lance un dé à six faces alors que Raph lance un dé à sept faces. Eva et Raph lancent les dés en même temps. On note $N$ le rang d'apparition du premier 1 chez Eva ou chez Raph.

##### Question 1

* Soit $N_E$ le rang d'apparition du premier 1 chez Eva. Déterminer la probabilité de l'événement $(N_E > k)$, pour tout $k \geq 1$. Quelle est la loi de $N_E$ ?

##### Question 2

* Calculer la probabilité de l'événement $(N > k)$, pour tout $k \geq 1$. Quelle est la loi de $N$ ?


##### Question 3

* Le premier 1 gagne la partie. Quelle est la probabilité pour que Eva gagne ? 

##### Question 4

* Quelle est la probabilité de match nul ?

##### Question 5

* Calculer la probabilité que la partie a duré moins de 3 manches sachant qu'Eva a gagné.



** **

#### Problème 2

On dit que $U$ est une variable aléatoire de loi uniforme sur l'intervalle [0,1] si
$$
\forall 0 \leq a \leq b  \leq 1 \, , \quad  \mbox{P} ( U \in [a,b)) = b-a .
$$
Soit $U$ et $V$ deux variables aléatoires indépendantes de loi uniforme sur l'intervalle [0,1]. On définit la variable $W$ de la manière suivante. Si $U < 1/4$, $W$ est égale à $V$, sinon $W$ est égale à $\sqrt{V}$ .

  
##### Question 1

*  Calculer la probabilité que la variable aléatoire $W$ soit inférieure ou égale à $1/3$.  


  
##### Question 2

*  Calculer l'espérance de la variable aléatoire $W^2$.  



** **

#### Problème 3 


Soit $X$ une variable aléatoire de loi uniforme sur (0,1). Soit $Y$ une variable aléatoire dont la loi conditionnelle sachant $X = x$ est la loi uniforme sur $(0, x)$.
On pose $Z = X + Y$.

##### Question 1

*  Calculer l'espérance de la variable aléatoire $Z$.  

