--- 
title: "Cours 3"
output: html_document 
---

** **

#### [Espérance d'une variable aléatoire](https://francoio.github.io/)


##### Variable de Bernoulli (ou variable indicatrice)

On note $\mathbb{1}_A$ la variable aléatoire égale à 1 si $A$ se réalise, 0 sinon.  

* Par définition, nous avons

$$
\mathbb{E}[\mathbb{1}_A] = {\rm P}(A). 
$$

** ** 

#####  Variable étagée

Soit $\alpha_1, \dots ,\alpha_n$, $n$ **coefficients positifs** et $A_1, \dots , A_n$, $n$ événements. On appelle variable étagée, la variable  

$$ X = \sum_{i = 1}^n \alpha_i \, \mathbb{1}_{A_i} \, . 
$$

* Par définition, nous avons 

$$
\mathbb{E}[X] = \sum_{i = 1}^n \alpha_i \,  {\rm P}(A_i). 
$$
 

** **

#### Espérance d'une variable aléatoire

* Soit $X>0$ et $X_n$ une suite de variables étagées qui converge en croissant vers $X$. Par définition, nous avons 

$$
\mathbb{E}[X] = \lim_{n \to \infty} \mathbb{E}[X_n].
$$

* Soit $X$ une variable aléatoire réelle. On dit que $X$ est **intégrable** si $\mathbb{E}[|X|]<\infty$. Dans ce cas, nous avons

$$
\mathbb{E}[X] =  \mathbb{E}[\max(0,X)] - \mathbb{E}[ -\min(0,X)] \,. 
$$ 

** ** 

#### Espérance conditionnelle sachant $B$

Soit $B$ un événement de probabilité non-nulle. L'espérance conditionnelle de la variable $X$ sachant $B$, est l'espérance prise par rapport à la mesure de probabilité conditionnelle P($A|B$)

* Nous avons en particulier, pour toute variable étagée $X$,

$$
\mathbb{E}[X|B] = \sum_{i = 1}^n \alpha_i \,  {\rm P}(A_i|B). 
$$

** ** 

#### Convergence monotone 

Soit $X_n$ une suite de variables positives qui converge en croissant vers $X$. 

* Nous avons

$$
\mathbb{E}[\lim_{n \to \infty} X_n] = \lim_{n \to \infty} \mathbb{E}[X_n] \, . 
$$

  

